// INVENTARIO BASE DE STOCK DISPONIBLE - LINK INVERSIONES
// Estructura: Proyecto - Unidades - Valuación (USD / ARS)

export const DEFAULT_STOCK_UNITS = [
  // ── + DUO PROYECTO ──
  {
    id: "duo-01",
    proyecto: "+ DUO Proyecto",
    unidad: "Torre 1 · Piso 02 - Depto A",
    tipologia: "2 Dormitorios",
    piso: "Piso 2",
    orientacion: "Frente Norte",
    m2_propios: 68.5,
    m2_totales: 78.0,
    precio_usd: 126725,
    precio_m2_usd: 1850,
    estado: "Disponible",
    observaciones: "Balcón con asador, suite principal y cochera opcional.",
    entrega_estimada: "Diciembre 2027"
  },
  {
    id: "duo-02",
    proyecto: "+ DUO Proyecto",
    unidad: "Torre 1 · Piso 03 - Depto B",
    tipologia: "1 Dormitorio",
    piso: "Piso 3",
    orientacion: "Contrafrente Abierto",
    m2_propios: 48.0,
    m2_totales: 55.0,
    precio_usd: 88800,
    precio_m2_usd: 1850,
    estado: "Disponible",
    observaciones: "Cocina integrada equipada, balcón corrido.",
    entrega_estimada: "Diciembre 2027"
  },
  {
    id: "duo-03",
    proyecto: "+ DUO Proyecto",
    unidad: "Torre 1 · Piso 05 - Depto C",
    tipologia: "1 Dormitorio",
    piso: "Piso 5",
    orientacion: "Frente",
    m2_propios: 52.0,
    m2_totales: 59.5,
    precio_usd: 98800,
    precio_m2_usd: 1900,
    estado: "Disponible",
    observaciones: "Vista despejada, terminaciones prémium.",
    entrega_estimada: "Diciembre 2027"
  },
  {
    id: "duo-04",
    proyecto: "+ DUO Proyecto",
    unidad: "Torre 1 · Piso 07 - Depto A",
    tipologia: "2 Dormitorios",
    piso: "Piso 7",
    orientacion: "Frente Panorámico",
    m2_propios: 72.0,
    m2_totales: 83.0,
    precio_usd: 140400,
    precio_m2_usd: 1950,
    estado: "Disponible",
    observaciones: "Doble balcón, vestidor, carpintería DVH.",
    entrega_estimada: "Diciembre 2027"
  },
  {
    id: "duo-05",
    proyecto: "+ DUO Proyecto",
    unidad: "Torre 1 · Piso 09 - Depto D",
    tipologia: "3 Dormitorios",
    piso: "Piso 9",
    orientacion: "Esquina Noroeste",
    m2_propios: 104.0,
    m2_totales: 118.0,
    precio_usd: 218400,
    precio_m2_usd: 2100,
    estado: "Disponible",
    observaciones: "Semipiso exclusivo con asador propio y baulera.",
    entrega_estimada: "Diciembre 2027"
  },
  {
    id: "duo-06",
    proyecto: "+ DUO Proyecto",
    unidad: "Torre 2 · Piso 04 - Depto B",
    tipologia: "1 Dormitorio",
    piso: "Piso 4",
    orientacion: "Lateral",
    m2_propios: 47.5,
    m2_totales: 54.0,
    precio_usd: 87875,
    precio_m2_usd: 1850,
    estado: "Disponible",
    observaciones: "Excelente rentabilidad estimada en pozo.",
    entrega_estimada: "Diciembre 2027"
  },
  {
    id: "duo-07",
    proyecto: "+ DUO Proyecto",
    unidad: "Planta Baja · Local Comercial L-01",
    tipologia: "Local Comercial",
    piso: "PB",
    orientacion: "Frente Calle Principal",
    m2_propios: 85.0,
    m2_totales: 95.0,
    precio_usd: 195500,
    precio_m2_usd: 2300,
    estado: "Disponible",
    observaciones: "Vidriera doble altura, apto gastronomía o comercio.",
    entrega_estimada: "Diciembre 2027"
  },
  {
    id: "duo-08",
    proyecto: "+ DUO Proyecto",
    unidad: "Subsuelo 1 · Cochera C-14",
    tipologia: "Cochera",
    piso: "SS1",
    orientacion: "Acceso rampa fija",
    m2_propios: 14.0,
    m2_totales: 18.0,
    precio_usd: 18000,
    precio_m2_usd: 1285,
    estado: "Disponible",
    observaciones: "Cochera cubierta con portón automatizado.",
    entrega_estimada: "Diciembre 2027"
  },
  {
    id: "duo-09",
    proyecto: "+ DUO Proyecto",
    unidad: "Torre 2 · Piso 06 - Depto A",
    tipologia: "2 Dormitorios",
    piso: "Piso 6",
    orientacion: "Frente",
    m2_propios: 70.0,
    m2_totales: 80.0,
    precio_usd: 133000,
    precio_m2_usd: 1900,
    estado: "Reservado",
    observaciones: "Reserva seña 10% ingresada.",
    entrega_estimada: "Diciembre 2027"
  },

  // ── TORRE GREEN PROYECTO ──
  {
    id: "green-01",
    proyecto: "Torre Green Proyecto",
    unidad: "Piso 02 - Depto 201",
    tipologia: "1 Dormitorio",
    piso: "Piso 2",
    orientacion: "Frente Verde",
    m2_propios: 50.0,
    m2_totales: 58.0,
    precio_usd: 95000,
    precio_m2_usd: 1900,
    estado: "Disponible",
    observaciones: "Diseño sustentable, terrazas verdes comunes.",
    entrega_estimada: "Octubre 2027"
  },
  {
    id: "green-02",
    proyecto: "Torre Green Proyecto",
    unidad: "Piso 04 - Depto 402",
    tipologia: "1 Dormitorio",
    piso: "Piso 4",
    orientacion: "Contrafrente",
    m2_propios: 46.5,
    m2_totales: 53.0,
    precio_usd: 88350,
    precio_m2_usd: 1900,
    estado: "Disponible",
    observaciones: "Iluminación natural, muebles bajo mesada incluidos.",
    entrega_estimada: "Octubre 2027"
  },
  {
    id: "green-03",
    proyecto: "Torre Green Proyecto",
    unidad: "Piso 06 - Depto 601",
    tipologia: "2 Dormitorios",
    piso: "Piso 6",
    orientacion: "Frente",
    m2_propios: 74.0,
    m2_totales: 84.5,
    precio_usd: 148000,
    precio_m2_usd: 2000,
    estado: "Disponible",
    observaciones: "2 baños completos, suite con vestidor.",
    entrega_estimada: "Octubre 2027"
  },
  {
    id: "green-04",
    proyecto: "Torre Green Proyecto",
    unidad: "Piso 08 - Depto 803",
    tipologia: "2 Dormitorios",
    piso: "Piso 8",
    orientacion: "Norte",
    m2_propios: 71.0,
    m2_totales: 81.0,
    precio_usd: 142000,
    precio_m2_usd: 2000,
    estado: "Disponible",
    observaciones: "Pisos porcelanato, preinstalación aire acondicionado.",
    entrega_estimada: "Octubre 2027"
  },
  {
    id: "green-05",
    proyecto: "Torre Green Proyecto",
    unidad: "Piso 11 - Semipiso 1101",
    tipologia: "3 Dormitorios",
    piso: "Piso 11",
    orientacion: "Frente Panorámico 180°",
    m2_propios: 115.0,
    m2_totales: 130.0,
    precio_usd: 253000,
    precio_m2_usd: 2200,
    estado: "Disponible",
    observaciones: "Palier semiprivado, master suite, hidromasaje, parrilla.",
    entrega_estimada: "Octubre 2027"
  },
  {
    id: "green-06",
    proyecto: "Torre Green Proyecto",
    unidad: "Subsuelo · Cochera G-08",
    tipologia: "Cochera",
    piso: "SS1",
    orientacion: "Cubierta",
    m2_propios: 14.5,
    m2_totales: 18.5,
    precio_usd: 19000,
    precio_m2_usd: 1310,
    estado: "Disponible",
    observaciones: "Cochera cubierta con fácil maniobrabilidad.",
    entrega_estimada: "Octubre 2027"
  },
  {
    id: "green-07",
    proyecto: "Torre Green Proyecto",
    unidad: "Subsuelo · Cochera G-15",
    tipologia: "Cochera",
    piso: "SS1",
    orientacion: "Cubierta",
    m2_propios: 14.5,
    m2_totales: 18.5,
    precio_usd: 19000,
    precio_m2_usd: 1310,
    estado: "Disponible",
    observaciones: "Cochera contigua al ascensor principal.",
    entrega_estimada: "Octubre 2027"
  },

  // ── AURIA PROYECTO (MARCOS PAZ 82) ──
  {
    id: "auria-01",
    proyecto: "Auria Proyecto",
    unidad: "Piso 01 - Depto 102",
    tipologia: "1 Dormitorio",
    piso: "Piso 1",
    orientacion: "Frente con Patio",
    m2_propios: 55.0,
    m2_totales: 65.0,
    precio_usd: 104500,
    precio_m2_usd: 1900,
    estado: "Disponible",
    observaciones: "Unidad con patio privado aterrazado de 15m².",
    entrega_estimada: "Junio 2028"
  },
  {
    id: "auria-02",
    proyecto: "Auria Proyecto",
    unidad: "Piso 03 - Depto 301",
    tipologia: "1 Dormitorio",
    piso: "Piso 3",
    orientacion: "Frente",
    m2_propios: 49.0,
    m2_totales: 56.0,
    precio_usd: 95550,
    precio_m2_usd: 1950,
    estado: "Disponible",
    observaciones: "Preventa pozo con plan de financiación flexible.",
    entrega_estimada: "Junio 2028"
  },
  {
    id: "auria-03",
    proyecto: "Auria Proyecto",
    unidad: "Piso 04 - Depto 402",
    tipologia: "2 Dormitorios",
    piso: "Piso 4",
    orientacion: "Contrafrente Silencioso",
    m2_propios: 75.0,
    m2_totales: 86.0,
    precio_usd: 150000,
    precio_m2_usd: 2000,
    estado: "Disponible",
    observaciones: "Suite principal, placard piso a techo.",
    entrega_estimada: "Junio 2028"
  },
  {
    id: "auria-04",
    proyecto: "Auria Proyecto",
    unidad: "Piso 07 - Depto 701",
    tipologia: "2 Dormitorios",
    piso: "Piso 7",
    orientacion: "Frente Alto",
    m2_propios: 78.0,
    m2_totales: 89.0,
    precio_usd: 163800,
    precio_m2_usd: 2100,
    estado: "Disponible",
    observaciones: "Vista panorámica, balcón terraza con asador.",
    entrega_estimada: "Junio 2028"
  },
  {
    id: "auria-05",
    proyecto: "Auria Proyecto",
    unidad: "Piso 09 - Penthouse 901",
    tipologia: "3 Dormitorios",
    piso: "Piso 9",
    orientacion: "Frente Exclusivo",
    m2_propios: 122.0,
    m2_totales: 142.0,
    precio_usd: 280600,
    precio_m2_usd: 2300,
    estado: "Disponible",
    observaciones: "Piscina propia en terraza, domótica integrada.",
    entrega_estimada: "Junio 2028"
  },
  {
    id: "auria-06",
    proyecto: "Auria Proyecto",
    unidad: "Planta Baja · Local Comercial L-02",
    tipologia: "Local Comercial",
    piso: "PB",
    orientacion: "Frente Calle",
    m2_propios: 92.0,
    m2_totales: 105.0,
    precio_usd: 220800,
    precio_m2_usd: 2400,
    estado: "Disponible",
    observaciones: "Punto de alto tránsito peatonal y vehicular.",
    entrega_estimada: "Junio 2028"
  },

  // ── CUPO LINK # 300 ──
  {
    id: "l300-01",
    proyecto: "Cupo Link # 300",
    unidad: "Torre 1 · Piso 03 - Depto 3C",
    tipologia: "1 Dormitorio",
    piso: "Piso 3",
    orientacion: "Contrafrente",
    m2_propios: 45.0,
    m2_totales: 52.0,
    precio_usd: 78750,
    precio_m2_usd: 1750,
    estado: "Disponible",
    observaciones: "Entrega programada con cuotas restantes transferibles.",
    entrega_estimada: "Marzo 2027"
  },
  {
    id: "l300-02",
    proyecto: "Cupo Link # 300",
    unidad: "Torre 1 · Piso 06 - Depto 6A",
    tipologia: "2 Dormitorios",
    piso: "Piso 6",
    orientacion: "Frente",
    m2_propios: 67.0,
    m2_totales: 76.5,
    precio_usd: 123950,
    precio_m2_usd: 1850,
    estado: "Disponible",
    observaciones: "Living comedor amplio, excelente ventilación cruzada.",
    entrega_estimada: "Marzo 2027"
  },
  {
    id: "l300-03",
    proyecto: "Cupo Link # 300",
    unidad: "Torre 2 · Piso 04 - Depto 4B",
    tipologia: "Monoambiente",
    piso: "Piso 4",
    orientacion: "Lateral",
    m2_propios: 34.0,
    m2_totales: 39.0,
    precio_usd: 59500,
    precio_m2_usd: 1750,
    estado: "Disponible",
    observaciones: "Ideal inversión para alquiler temporario o profesional.",
    entrega_estimada: "Marzo 2027"
  },
  {
    id: "l300-04",
    proyecto: "Cupo Link # 300",
    unidad: "Subsuelo · Cochera C-05",
    tipologia: "Cochera",
    piso: "SS1",
    orientacion: "Rampa",
    m2_propios: 13.5,
    m2_totales: 17.0,
    precio_usd: 16500,
    precio_m2_usd: 1220,
    estado: "Disponible",
    observaciones: "Cochera fija cubierta.",
    entrega_estimada: "Marzo 2027"
  },

  // ── CUPO LINK BOULEVARD ──
  {
    id: "lboul-01",
    proyecto: "Cupo Link Boulevard",
    unidad: "Piso 02 - Depto 2A",
    tipologia: "2 Dormitorios",
    piso: "Piso 2",
    orientacion: "Frente Boulevard",
    m2_propios: 70.0,
    m2_totales: 80.0,
    precio_usd: 133000,
    precio_m2_usd: 1900,
    estado: "Disponible",
    observaciones: "Vista arbolada al boulevard, balcón terraza.",
    entrega_estimada: "Mayo 2027"
  },
  {
    id: "lboul-02",
    proyecto: "Cupo Link Boulevard",
    unidad: "Piso 05 - Depto 5B",
    tipologia: "1 Dormitorio",
    piso: "Piso 5",
    orientacion: "Contrafrente Norte",
    m2_propios: 51.0,
    m2_totales: 58.0,
    precio_usd: 96900,
    precio_m2_usd: 1900,
    estado: "Disponible",
    observaciones: "Mucha luz todo el día, placares terminados.",
    entrega_estimada: "Mayo 2027"
  },
  {
    id: "lboul-03",
    proyecto: "Cupo Link Boulevard",
    unidad: "Piso 08 - Depto 8A",
    tipologia: "3 Dormitorios",
    piso: "Piso 8",
    orientacion: "Piso Exclusivo",
    m2_propios: 110.0,
    m2_totales: 125.0,
    precio_usd: 231000,
    precio_m2_usd: 2100,
    estado: "Disponible",
    observaciones: "Piso exclusivo con ascensor codificado y doble cochera.",
    entrega_estimada: "Mayo 2027"
  },
  {
    id: "lboul-04",
    proyecto: "Cupo Link Boulevard",
    unidad: "PB · Local Comercial L-01",
    tipologia: "Local Comercial",
    piso: "PB",
    orientacion: "Boulevard",
    m2_propios: 75.0,
    m2_totales: 84.0,
    precio_usd: 172500,
    precio_m2_usd: 2300,
    estado: "Disponible",
    observaciones: "Excelente visibilidad sobre rotonda principal.",
    entrega_estimada: "Mayo 2027"
  },

  // ── CUPO LINK NEUQUÉN ──
  {
    id: "lneu-01",
    proyecto: "Cupo Link Neuquén",
    unidad: "Piso 03 - Depto 302",
    tipologia: "1 Dormitorio",
    piso: "Piso 3",
    orientacion: "Norte",
    m2_propios: 48.0,
    m2_totales: 55.0,
    precio_usd: 91200,
    precio_m2_usd: 1900,
    estado: "Disponible",
    observaciones: "Zona de alta demanda petrolera/corporativa.",
    entrega_estimada: "Diciembre 2027"
  },
  {
    id: "lneu-02",
    proyecto: "Cupo Link Neuquén",
    unidad: "Piso 05 - Depto 501",
    tipologia: "2 Dormitorios",
    piso: "Piso 5",
    orientacion: "Frente",
    m2_propios: 72.0,
    m2_totales: 82.0,
    precio_usd: 144000,
    precio_m2_usd: 2000,
    estado: "Disponible",
    observaciones: "Renta proyectada en dólares superior al 8% anual.",
    entrega_estimada: "Diciembre 2027"
  },
  {
    id: "lneu-03",
    proyecto: "Cupo Link Neuquén",
    unidad: "Piso 07 - Depto 704",
    tipologia: "Monoambiente",
    piso: "Piso 7",
    orientacion: "Este",
    m2_propios: 36.0,
    m2_totales: 42.0,
    precio_usd: 68400,
    precio_m2_usd: 1900,
    estado: "Disponible",
    observaciones: "Equipado full para alquiler corporativo.",
    entrega_estimada: "Diciembre 2027"
  }
];

export const PROYECTOS_STOCK = [
  "+ DUO Proyecto",
  "Torre Green Proyecto",
  "Auria Proyecto",
  "Cupo Link # 300",
  "Cupo Link Boulevard",
  "Cupo Link Neuquén"
];

export const TIPOLOGIAS_STOCK = [
  "Monoambiente",
  "1 Dormitorio",
  "2 Dormitorios",
  "3 Dormitorios",
  "Cochera",
  "Local Comercial",
  "Oficina"
];
